Repository COSC481W-2023Fall/planned-out, pull requests merged in 2023-10, with the labels that each got.

#3 refactor: Create react app
  planned-out/.gitignore
  planned-out/README.md
  planned-out/package-lock.json
  planned-out/package.json
  planned-out/public/favicon.ico
  planned-out/public/index.html
  planned-out/public/logo192.png
  planned-out/public/logo512.png
  planned-out/public/manifest.json
  planned-out/public/robots.txt
  planned-out/src/App.css
  planned-out/src/App.js
  planned-out/src/App.test.js
  planned-out/src/index.css
  planned-out/src/index.js
  planned-out/src/logo.svg
  planned-out/src/reportWebVitals.js
  planned-out/src/setupTests.js
Labels: sprint-0

#4 feat: Setup Frontend Testing
  .gitignore
  README.md
  back-end/message.json
  back-end/package-lock.json
  back-end/package.json
  back-end/server.mjs
  front-end/ReactREADME.md
  front-end/src/App.js
  front-end/src/App.test.js
  front-end/src/tests/App.test.js
  front-end/src/tests/example.test.js
  package-lock.json
Labels: documentation, sprint-0

#11 feat: Implement basic homepage shell
  front-end/package-lock.json
  front-end/package.json
  front-end/src/index.css
  front-end/src/index.js
  front-end/src/pages/Home.js
  front-end/src/pages/Layout.js
Labels: feature, UI-design, sprint-1

#12 feat: created database connection file
  back-end/db/conn.mjs
  back-end/server.mjs
  front-end/package-lock.json
  front-end/package.json
  front-end/src/setupTests.js
  front-end/src/tests/db.test.js
Labels: feature

#13 feat: added task view
  back-end/server.mjs
  front-end/src/index.css
  front-end/src/pages/Home.js
  front-end/src/tests/task_view_backend.test.js
  front-end/src/tests/task_view_frontend.test.js
Labels: feature, sprint-1

#31 feat: Implement shell for Settings page
  front-end/src/components/SettingsAppearance.js
  front-end/src/components/SettingsPrivacy.js
  front-end/src/components/SettingsProfile.js
  front-end/src/components/SettingsSecurity.js
  front-end/src/index.js
  front-end/src/pages/Layout.js
  front-end/src/pages/Settings.css
  front-end/src/pages/Settings.js
Labels: feature, UI-design, UX, sprint-2

#33 Feat: Registration Page
  front-end/src/components/RegistrationForm.js
  front-end/src/index.js
  front-end/src/pages/Layout.js
  front-end/src/pages/Registration.js
  front-end/src/pages/TaskCard.css
  front-end/src/pages/registration.css
Labels: feature, UI-design, UX, sprint-2

#34 fix: Automatically update the task list after adding a task
  back-end/server.mjs
  front-end/package-lock.json
Labels: front-end-bug, optimization, sprint-2
